local UI = loadstring(game:HttpGet("https://raw.githubusercontent.com/alo227/AloHub/main/GUILibrary.lua"))()

local window = UI:CreateWindow("Alo Hub")

local main = window:CreateTab("Main")
main:AddSection("Core")
main:AddButton("Test Button", function()
	print("Hello from Alo Hub")
end)

main:AddToggle("Example Toggle", false, function(state)
	print("Example Toggle:", state)
end)

main:AddLabel("Status: Ready")

local combat = window:CreateTab("Combat")
combat:AddSection("Placeholders")
combat:AddButton("Attack Placeholder", function()
	print("Attack placeholder")
end)
combat:AddToggle("Auto Attack Placeholder", false, function(state)
	print("Auto Attack:", state)
end)
combat:AddButton("Mob List Placeholder", function()
	print("Mob list placeholder")
end)

local debug = window:CreateTab("Debug")
debug:AddSection("Remote Tools")
debug:AddButton("Open Remote Logger Placeholder", function()
	print("Remote logger placeholder")
end)
debug:AddToggle("Hook FireServer Placeholder", false, function(state)
	print("Hook FireServer:", state)
end)
debug:AddButton("Copy Last Call Placeholder", function()
	print("Copy last call placeholder")
end)